
---- Colegio
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	1	,'	IE Santa Rosa (primaria)	-	Trujillo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	2	,'	IE Santa Inés	-	Guadalupe	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	3	,'	IE La Asunción	-	Trujillo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	4	,'	IE Santa Rosa (secundaria)	-	Trujillo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	5	,'	IE San Martín de Porres	-	El Porvenir	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	6	,'	IE Santo Domingo de Guzmán	-	Moche	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	7	,'	IE Sagrada Familia	-	Sullana - Cieneguillo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	8	,'	IE Las Capullanas	-	Sullana	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	9	,'	IE San Martín de Porres	-	Cusco	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	10	,'	IE San Martín de Porres	-	California	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	11	,'	IE Sagrado Corazón	-	Arequipa	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	12	,'	IE Mater Christi	-	Surco	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	13	,'	IE Nuestra Sra. del Rosario	-	Chiclayo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	14	,'	IE María Inmaculada	-	Ferreñafe	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	15	,'	IE Beata Imelda	-	Chiclayo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	16	,'	IE San Martín de Porres	-	Reque	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	17	,'	IE Nuestra Sra. de la Asunción	-	Cutervo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	18	,'	IE Nuestra Sra. de Lourdes Secundaria	-	Bambamarca	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	19	,'	IE Nuestra Sra. de Lourdes Primaria	-	Bambamarca	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	20	,'	IE Nuestra Sra. del Rosario	-	Cajabamba	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	21	,'	IE Reina de los Ángeles	-	La Molina	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	22	,'	IE Reina del Santísimo Rosario	-	Chincha	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	23	,'	IE San Martín de Porres	-	Chincha	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	24	,'	IE Santa Anita	-	Santa Anita	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	25	,'	IE Santa Rosa	-	San Isidro	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	26	,'	IE Rosa de Lima	-	Huancayo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	27	,'	IE Heroínas Toledo	-	Huancayo	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	28	,'	IE Santa Rosa de Lima	-	Villa el Salvador	',null,1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Colegio',	29	,'	IE San José	-	Chaclacayo	',null,1)

---- Area
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 1, 'Comunicación', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 2, 'Matemática', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 3, 'Personal Social (primaria)', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 4, 'Historia, Geografía y Economía', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 5, 'Formación Ciudadana y Cívica', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 6, 'Persona Familia y Relaciones Humana', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 7, 'Ciencia y Ambiente (inicial y primaria)', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 8, 'Ciencia Tecnología y Ambiente', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 9, 'Religión', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 10, 'Arte', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 11, 'Educación Física', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 12, 'Educación para el trabajo', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 13, 'Cómputo e informática', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 14, 'Tutoría', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Area', 15, 'Otras áreas y talleres', null, 1)


---- Nivel
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Nivel', 1, 'Inicial', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Nivel', 2, 'Primaria', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Nivel', 3, 'Secundaria', null, 1)

---- Grado
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 1, '2 años', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 2, '3 años', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 3, '4 años', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 4, '5 años', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 5, '1 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 6, '2 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 7, '3 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 8, '4 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 9, '5 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 10, '6 grado', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 11, '1 año', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 12, '2 año', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 13, '3 año', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 14, '4 año', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('Grado', 15, '5 año', 3, 1)

---- Competencia Lv
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CompetenciaLv', 1, 'CONTEMPLAR LA REALIDAD DESDE LA LUZ Y LA VERDAD', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CompetenciaLv', 2, 'PREDICAR A DIOS COMO LUZ Y VERDAD', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CompetenciaLv', 3, 'PROMOVER LA DIGNIDAD DEL HOMBRE PARA SU SALVACIÓN', null, 1)

---- Capacidad Lv
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CapacidadLv', 1, 'En proceso de elaboración', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CapacidadLv', 2, 'En proceso de elaboración', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('CapacidadLv', 3, 'En proceso de elaboración', 3, 1)

---- Metodologia Lv
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('MetodologiaLv', 1, 'En proceso de elaboración', null, 1)

---- Titulo Lv
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('TituloLv', 1, 'Titulo 1', null, 1)

---- Tema Lv
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('TemaLv', 1, 'Tema 1', 1, 1)

---- Virtud General
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 1, 'TEMPLANZA', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 2, 'ESPERANZA', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 3, 'PRUDENCIA', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 4, 'FE', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 5, 'CARIDAD', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 6, 'FORTALEZA', null, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudGeneral', 7, 'JUSTICIA', null, 1)

---- Virtud Especifica
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 1, 'Castidad', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 2, 'Modestia Sobriedad', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 3, 'Mansedumbre', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 4, 'Estudio', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 5, 'Humildad', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 6, 'Sencillez', 1, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 7, 'Alegría', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 8, 'Confianza - Providencia', 2, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 9, 'Ecuanimidad', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 10, 'Audacia', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 11, 'Tolerancia', 3, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 12, 'Fidelidad', 4, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 13, 'Obediencia', 4, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 14, 'Piedad', 4, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 15, 'Misericordia - Compasión', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 16, 'Generosidad', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 17, 'Servicio', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 18, 'Fraternidad', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 19, 'Veracidad', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 20, 'Honestidad', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 21, 'Paciencia', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 22, 'Perdón', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 23, 'Ternura', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 24, 'Amistad', 5, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 25, 'Abnegación', 6, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 26, 'Perseverancia', 6, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 27, 'Responsabilidad', 6, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 28, 'Laboriosidad', 6, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 29, 'Paz', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 30, 'Bien común', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 31, 'Libertad', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 32, 'Respeto', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 33, 'Orden', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 34, 'Puntualidad', 7, 1)
insert into Tabla(NombreTabla, Codigo, Valor, CodigoPadre, EsActivo)
values ('VirtudEspecifica', 35, 'Gratitud', 7, 1)

--Colegio
insert into [Colegio]([ColegioNombre],[ColegioDireccion], [ColegioTelefono])
values ('ColegioAdmin','Direccion1','telefono1')

--Usuario
insert into [dbo].[Usuario]([Usuario],[Nombres],[Apematerno], [Apepaterno], [Pass], [Correo], [ColegioId], [EsActivo])
values('admin','Usu1','Usu1','Usu1',PWDENCRYPT('123'),'usu@d.com',1,1)